### ISSUE TITLE
Cant compile template

### ISSUE THREAD

**Issue by EATREVITPOOPCAD** [jeremytammik/VisualStudioRevitAddinWizard#13]
`CS5001	Program does not contain a static 'Main' method suitable for an entry point`

Tried on Release, Debug, Debug 1

**Comment by jeremytammik** [comment]
A Revit add-in is a .NET class library, i.e., a .NET assembly DLL, not a stand-alone executable. 

Hence, it has no `Main` method.

**Comment by EATREVITPOOPCAD** [comment]
That was a silly issue, I gave up while burning midnight fuel... thanks! Compiled.

**Comment by EATREVITPOOPCAD** [comment]
Ok so now that I compile fine I get the following warnings. Looks like an issue loading Revit DLLs. I have the SDK installed but do not have Revit installed... could this cause an issue?

`1>C:\...\Microsoft.NET.Build.Extensions.NETFramework.targets(57,5): warning NETSDK1049: Resolved file has a bad image, no metadata, or is otherwise inaccessible. An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B) C:\...\autodesk.revit.sdk\2019.2.2.2001\ref\net47\RevitAPILink.dll
1>C:\...\Microsoft.NET.Build.Extensions\Microsoft.NET.Build.Extensions.NETFramework.targets(57,5): warning NETSDK1049: Resolved file has a bad image, no metadata, or is otherwise inaccessible. An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B) C:\...\autodesk.revit.sdk\2019.2.2.2001\ref\net47\RevitAPIUILink.dll
1>C:\...\Microsoft.NET.Build.Extensions\Microsoft.NET.Build.Extensions.NETFramework.targets(57,5): warning NETSDK1049: Resolved file has a bad image, no metadata, or is otherwise inaccessible. An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B) C:\...\autodesk.revit.sdk\2019.2.2.2001\ref\net47\RevitDB.dll
1>C:\...\Microsoft.NET.Build.Extensions\Microsoft.NET.Build.Extensions.NETFramework.targets(57,5): warning NETSDK1049: Resolved file has a bad image, no metadata, or is otherwise inaccessible. An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B) C:\...\autodesk.revit.sdk\2019.2.2.2001\ref\net47\RevitUI.dll
1>C:\...\Microsoft.Common.CurrentVersion.targets(2123,5): warning MSB3246: Resolved file has a bad image, no metadata, or is otherwise inaccessible. Could not load file or assembly 'RevitAPILink.dll' or one of its dependencies. The module was expected to contain an assembly manifest.
1>C:\...\Microsoft.Common.CurrentVersion.targets(2123,5): warning MSB3246: Resolved file has a bad image, no metadata, or is otherwise inaccessible. Could not load file or assembly 'RevitAPIUILink.dll' or one of its dependencies. The module was expected to contain an assembly manifest.
1>C:\...\Microsoft.Common.CurrentVersion.targets(2123,5): warning MSB3246: Resolved file has a bad image, no metadata, or is otherwise inaccessible. Could not load file or assembly 'RevitDB.dll' or one of its dependencies. The module was expected to contain an assembly manifest.
1>C:\...\Microsoft.Common.CurrentVersion.targets(2123,5): warning MSB3246: Resolved file has a bad image, no metadata, or is otherwise inaccessible. Could not load file or assembly 'RevitUI.dll' or one of its dependencies. The module was expected to contain an assembly manifest.`

**Comment by jeremytammik** [comment]
Yes, that will definitely be a problem.

The Revit SDK does not include the Revit API DLLs. 

The SDK contains nothing except documentation and sample source code.

The Revit API DLLs are included with the Revit product. Since you cannot load a Revit add-in without having Revit installed, it is a valid assumption that every attempt to compile a Revit add-in will always be performed on a Windows system with a Revit installation.

**Comment by EATREVITPOOPCAD** [comment]
I see, so I actually had the 2019 Revit API DLLs in the what would be Revit installation folder (I manually put them there), but I will try again with Revit fully installed... Going to put the pencil down until Monday though... Can't wait to get through this hurdle of targeting different Revit versions (I got stuck here for an embarrassing amount of time) so I can go back to tackling my long list of plugins I would like to make :D 
I will post my success / failures next week! thanks again

**Comment by jeremytammik** [comment]
Just having the Revit API DLLs in the what would be Revit installation folder is perfectly sufficient. I used to do that as well for a while. Since this thread is getting rather long and is not really a VisualStudioRevitAddinWizard issue, I would suggest continuing the discussion in the Revit API forum, so more other developers will see it and be able to participate if inclined. Thx!

**Comment by EATREVITPOOPCAD** [comment]
I Will do that... again thank you and sorry for annoying you with silly issues...  By the way, I recently discovered your blog, and I want to say I am a huge fan of your work!

**Comment by jeremytammik** [comment]
No problem, and thank you for your appreciation!
