### ISSUE TITLE
VisualStudio 2022 does not recognize template

### ISSUE THREAD

**Issue by jayDevel** [jeremytammik/VisualStudioRevitAddinWizard#14]
Hey,
I used the current 9f3b0a0 template batch with parameter "2022" but the created Template wasn't recognized by Visual Studio 2022.

The simple solution: In file ```TemplateRevitCs.vstemplate``` change the first line to Version 3: ```<VSTemplate Type="Project" Version="3.0.0"```

**Comment by jeremytammik** [comment]
Thank you for the information. Have you tested that and verified that it works? If so, could you possibly submit a pull request that implements that modification? Thank you!

**Comment by jayDevel** [comment]
The solution works for me, well. I can submit a pull request, but the question arises: should the solution be compatible with previous VisualStudio versions? I don't know, whether my fix breaks the template for them.

**Comment by jayDevel** [comment]
I've also tested my solution with VisualStudio 2017 and 2019 and it works, too.

**Comment by jeremytammik** [comment]
wonderful! that should be enough backwards compatibility, i think. thank you!

**Comment by Danail-Momchilov** [comment]
Hi! it doesn't work for me. I changed the .bat file data to represent my templates location and Revit 2021, but nothing really happens once I run the file.

**Comment by jeremytammik** [comment]
Maybe the template location is a problem for you: https://github.com/jeremytammik/VisualStudioRevitAddinWizard#user-project-template-location

**Comment by angelromosandoval** [comment]
Hello, during the installation when I am in CMD I write: 
C:\VisualStudioRevitAddinWizard-master>install 2022
Install tries to install the Template in "Y:\Documents\Visual Studio...."
but I do not have "Y:\", (I have C:\)
How can I solve this problem?
