### ISSUE TITLE
Post-build steps fail for the Release target

### ISSUE THREAD

**Issue by martinjansa** [jeremytammik/VisualStudioRevitAddinWizard#4]
If a project generated from a template is built for the Release target, the post-build step fails as it copies the .dll always from the bin\Debug path. I'll suggest a fix for this.

**Comment by martinjansa** [comment]
I am not able to create my own branch to commit the fix, so I am attaching a patch (dump of my local commit):

commit 679f965a7daa8b56bfd15e6a29d5989214c5771e
Author: Martin Jansa <martin.jansa@seznam.cz>
Date:   Wed Jun 21 11:52:20 2017 +0200

    variables ProjectDir and OutputPath used in the post-build step to copy the right DLL version

diff --git a/cs/TemplateRevitCs.csproj b/cs/TemplateRevitCs.csproj
index c8db808..77f95bb 100644
--- a/cs/TemplateRevitCs.csproj
+++ b/cs/TemplateRevitCs.csproj
@@ -60,7 +60,7 @@
   <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
   <PropertyGroup>
     <PostBuildEvent>copy "$(ProjectDir)*.addin" "$(AppData)\Autodesk\REVIT\Addins\2018"
-copy "$(ProjectDir)bin\debug\*.dll" "$(AppData)\Autodesk\REVIT\Addins\2018"</PostBuildEvent>
+copy "$(ProjectDir)$(OutputPath)*.dll" "$(AppData)\Autodesk\REVIT\Addins\2018"</PostBuildEvent>
   </PropertyGroup>
   <!-- To modify your build process, add your task inside one of the targets below and uncomment it.
        Other similar extension points exist, see Microsoft.Common.targets.

**Comment by jeremytammik** [comment]
thank you, that makes sense. the normal way to do this is to fork my repo to your own copy, make your changes to that, and then submit a pull request for me to merge them back. that is a lot easier than working with a patch. give it a try and you will see how well it works and how little effort it is ofr all involved, both you and me. thank you!

**Comment by martinjansa** [comment]
Thank you, I will do the fork way for my educational purposes.

**Comment by jeremytammik** [comment]
thank you for the pull request! looks good to me.
