### ISSUE TITLE
install.bat requires ZIP + Fails unless VS 2015

### ISSUE THREAD

**Issue by cjm771** [jeremytammik/VisualStudioRevitAddinWizard#8]
I would just specify in your readme, that zip needs to be added to path variable if not already done? Im on windows10 and I guess it wasnt there! I also needed to edit the bat file  for visual studio 2017, it was set for 2015. 

Other than that thanks!

**Comment by jeremytammik** [comment]
Thank you very much for the valuable suggestion. 

It would help even more if you forked the repository, applied the fix you suggest, and submitted a pull request.

I am actually still using Visual Studio 2015 myself, so I cannot fix that aspect quite yet.

I am planning to update these wizards for Revit 2019 real soon now, so more fixes will be coming soon.

**Comment by jeremytammik** [comment]
No need for a pull request in this case, of course  :-)

Done.
